language: java
sudo: false
install: true

jdk:
  - oraclejdk11
install:
  - export TRAVIS_COMMIT_DESCRIPTION=`git log -n 1`
script:
  - mvn clean verify
  - chmod +x ./util/release.sh
  - ./util/release.sh;
cache:
  directories:
    - "$HOME/.m2/repository"